version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: anko_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - anko_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anko_api
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    depends_on:
      - postgres
    networks:
      - anko_network

volumes:
  postgres_data:

networks:
  anko_network:
    driver: bridge
